### PR TITLE
fix: remove broken LTR fallbacks. Fix #18

### LINKED ISSUE #18: Fallbacks for rounded values break in rtl context
### Describe the bug

The fallback values for e.g. `rounded-r` results in all corners being rounded when consumed in a `rtl` context.

which matches: https://github.com/thibaudcolas/tailwindcss-vanilla-rtl/blob/d550539e004b4b215baba8e3ca40ddb67f877956/src/corePlugins.js#L1498

### Which terms did you search for in the documentation and issue tracker?

[Readme#browser-support](https://github.com/thibaudcolas/tailwindcss-vanilla-rtl#browser-support)

### Environment

Latest Safari & Chrome

### Expected behavior

image

### Actual behavior

image

### Reproducible demo

https://codepen.io/larsenwork/pen/vYrxRzQ/c403ba8fd987a00355890de11107b14d

Or maybe I'm doing something wrong? 😅

### PR DESCRIPTION
**Pull request by larsenwork**
Removes LTR only fallbacks as they break in RTL context and `postcss-logical` is already a better solution for fallbacks. This simplifies the plugin and makes it more predictable (I humbly hope 😄)  

Closes https://github.com/thibaudcolas/tailwindcss-vanilla-rtl/issues/18

I've tried it out in a private repo and works just as expected.

### CODE REVIEW

File: src/corePlugins.js [hunk 1]
```diff
@@ -1071,21 +1071,20 @@ export let corePlugins = {
 
   /**
   * Logical Properties and Values: added with fallback.
```
Comment (thibaudcolas) [inline src/corePlugins.js:1073]:
```suggestion
  * Logical Properties and Values: overriding defaults.
```

**Review by thibaudcolas — APPROVED** [review]
Thank you @larsenwork, completely agree with you here. Change looks spot on aside from the extra comment needing updating.
